### ISSUE TITLE
Basic Core WYSIWYG (at least) Out of the box

### ISSUE THREAD

**Issue by darksolar1** [moxi9/phpfox-feature-requests#77] opened 2016-03-14 09:18 UTC
After having time to think about the overall package of phpfox. One of the things that just doesn't feel or seem right is placing yourself as the average user of a phpfox website. 

Although phpfox has a lot of great basic core functions. I think phpfox is missing the ball or (at least not seeing) the most important aspect of a social site and that is content generation that is done by the average non technical user. Now putting myself in the shoes of the average user, it is very difficult to generate high quality content on a phpfox site because it simply lacks very basic core functions to be able to format text content such as bold, center, left right, bullets, insert image in a certain area, insert hyperlink, etc...

You average user is not going to know bbcodes and not all bbcodes work with phpfox. So from the eyes of the average non technical user who likes to write will simply find it very frustrating to generate any content at all.

Now I hear the argument that it is applicable to for third parties to develop, but my argument is this; 
the "basic" WYSIWYG is not to take away from third party devs, but it is comparable to building a house that lack the basic necessities such as constructing the plumbing, but leaving out a very basic faucet to utilize that plumbing. So doing very simple things like getting water from the plumbing becomes a very frustrating task because there's no faucet. Now if I wanted a better faucet I would get a fancy aftermarket faucet, but I at the very least need  faucet. Otherwise all that great plumbing doesn't really do me much good.

I hope the analogy conveys the point about the very basic functions out of the box... and if a site owner wanted something better they have the option of getting a 3rd party dev'd product.

**Comment by Data66PF** [comment] 2016-03-19 10:28
Though I desperately need this for my own author site, it is not something we are going to do as it is not a small core improvement. The issue is security. I know other scripts have these but, any sort of editor actually does open a site to hacks. Before I reluctantly close this though, I'll ask one more time if there is any way for us to include a few basic editing options but I was already told No once.

**Comment by lueung** [comment] 2016-03-23 22:17
I see github has a pretty nice basic setup. Something github would be perfect.

**Comment by supremeSEO** [comment] 2016-04-21 14:52
This is an issue phpFox must address. Lueung is ABSOLUTELY correct. Not having an editor harkens back to the 90's. This function is critical to user generated content. Without it people WILL migrate to other more advanced sites. Before Fox considers upgrading they need to insure ALL functionality or semblence of still exists. Upgrades are suppose to move things forward not backward. All the way back in v2 there were both a core bbcode editor and an HTML editor. Now in V4 there is not? REALLY. That is moving backward.

I understand security is a huge and ever growing issue. Whenever a community dies off due to lack of functionality however that negates the need for security. Functionality must go hand in hand with security when upgrading. Without both there is little value in either.

**Comment by Data66PF** [comment] 2016-04-22 10:16
Please read our terms before posting any bugs, feature request or comments as we've updated them and will start removing or editing as mentioned in the readme for each section - bugs or features.

**Closed by Data66PF** 2016-04-22 10:16 UTC
